### PR TITLE
WebP animations

### PR DESCRIPTION
**Pull request by blino**
This adds WebP animations support and required fixes to support animations from YouTube 2017 tests: https://qual-e.appspot.com/awebp.html

### CODE REVIEW

**Comment by blino** [comment]
Please do not attempt to merge, this is posted for initial review/testing only.
This work was done on the 20170228 branch.

I will submit the patches in upstream WebKit.

**Comment by magomez** [comment]
Thanks for working on this @blino!!
At first sight it looks good. Could you create a bug upstream and send the patch there so other people can review it too?

**Comment by blino** [comment]
Thanks @magomez for the early review, I'll push this upstream this week.

**Comment by blino** [comment]
The last push is mostly a rebase of the commits.
There are still a few things to cleanup before proposing this upstream.

**Comment by blino** [comment]
Patch submitted to (already existing) upstream bug report: https://bugs.webkit.org/show_bug.cgi?id=113124

**Comment by blino** [comment]
This has been merged after the rework from @magomez 
Thanks!

**Pull request closed without merging**
