### PR TITLE
[EME] fix crash on attempt to decrypt without cdm instance set yet

### PR DESCRIPTION
**Pull request by emutavchi**

### CODE REVIEW

**Comment by calvaris** [comment]
This should not be necessary. The player always notifies of a new CDMInstance before suggesting drm-attempt-to-decrypt-with-instance. Besides, this code should make that impossible, at least in Debug mode:

```
void MediaPlayerPrivateGStreamerBase::attemptToDecryptWithInstance(const CDMInstance& instance)
{
    ASSERT(isMainThread());
    ASSERT(m_cdmInstance.get() == &instance);
    GST_TRACE("instance %p, current stored %p", &instance, m_cdmInstance.get());
    attemptToDecryptWithLocalInstance();
}

void MediaPlayerPrivateGStreamerBase::attemptToDecryptWithLocalInstance()
{
    GST_TRACE("dispatching attempt to decrypt with local instance");
    dispatchDecryptionStructure(GUniquePtr<GstStructure>(gst_structure_new_empty("drm-attempt-to-decrypt-with-local-instance")));
}
```

Please, submit a backtrace in Debug mode of hitting `ASSERT(m_cdmInstance.get() == &instance);` and then we can think of something.

**Comment by calvaris** [comment]
Ok, I see. You're right.

Fortunately this code will be obsolete very soon, so I prefer to avoid merging this. Please have a look once we do our next merge.

**Comment by emutavchi** [comment]
Thanks for the info. I'll create an issue for tracking this, so we'll know when the merge is completed.

**Comment by emutavchi** [comment]
Created https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/527

**Pull request closed without merging**
